// Canonical pawaPay status and failure codes for type-safe usage across the codebase
// Update all status/failure code handling to use these enums

export enum PawapayStatusCode {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REJECTED = 'REJECTED',
}

export enum PawapayTechnicalFailureCode {
  NO_AUTHENTICATION = 'NO_AUTHENTICATION',
  AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
  AUTHORISATION_ERROR = 'AUTHORISATION_ERROR',
  HTTP_SIGNATURE_ERROR = 'HTTP_SIGNATURE_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  MISSING_PARAMETER = 'MISSING_PARAMETER',
  UNSUPPORTED_PARAMETER = 'UNSUPPORTED_PARAMETER',
  INVALID_PARAMETER = 'INVALID_PARAMETER',
  AMOUNT_OUT_OF_BOUNDS = 'AMOUNT_OUT_OF_BOUNDS',
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
  INVALID_CURRENCY = 'INVALID_CURRENCY',
  INVALID_PROVIDER = 'INVALID_PROVIDER',
  DUPLICATE_METADATA_FIELD = 'DUPLICATE_METADATA_FIELD',
  DEPOSITS_NOT_ALLOWED = 'DEPOSITS_NOT_ALLOWED',
  PAYOUTS_NOT_ALLOWED = 'PAYOUTS_NOT_ALLOWED',
  REFUNDS_NOT_ALLOWED = 'REFUNDS_NOT_ALLOWED',
  PROVIDER_TEMPORARILY_UNAVAILABLE = 'PROVIDER_TEMPORARILY_UNAVAILABLE',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}

export enum PawapayTransactionFailureCode {
  PAYMENT_NOT_APPROVED = 'PAYMENT_NOT_APPROVED',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  PAYMENT_IN_PROGRESS = 'PAYMENT_IN_PROGRESS',
  PAYER_NOT_FOUND = 'PAYER_NOT_FOUND',
  RECIPIENT_NOT_FOUND = 'RECIPIENT_NOT_FOUND',
  MANUALLY_CANCELLED = 'MANUALLY_CANCELLED',
  PAWAPAY_WALLET_OUT_OF_FUNDS = 'PAWAPAY_WALLET_OUT_OF_FUNDS',
  DEPOSIT_ALREADY_REFUNDED = 'DEPOSIT_ALREADY_REFUNDED',
  AMOUNT_TOO_LARGE = 'AMOUNT_TOO_LARGE',
  REFUND_IN_PROGRESS = 'REFUND_IN_PROGRESS',
  WALLET_LIMIT_REACHED = 'WALLET_LIMIT_REACHED',
  UNSPECIFIED_FAILURE = 'UNSPECIFIED_FAILURE',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
