export enum MtnErrorReasonCode {
  PAYEE_NOT_FOUND = 'PAYEE_NOT_FOUND',
  PAYER_NOT_FOUND = 'PAYER_NOT_FOUND',
  NOT_ALLOWED = 'NOT_ALLOWED',
  NOT_ALLOWED_TARGET_ENVIRONMENT = 'NOT_ALLOWED_TARGET_ENVIRONMENT',
  INVALID_CALLBACK_URL_HOST = 'INVALID_CALLBACK_URL_HOST',
  INVALID_CURRENCY = 'INVALID_CURRENCY',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INTERNAL_PROCESSING_ERROR = 'INTERNAL_PROCESSING_ERROR',
  NOT_ENOUGH_FUNDS = 'NOT_ENOUGH_FUNDS',
  PAYER_LIMIT_REACHED = 'PAYER_LIMIT_REACHED',
  PAYEE_NOT_ALLOWED_TO_RECEIVE = 'PAYEE_NOT_ALLOWED_TO_RECEIVE',
  PAYMENT_NOT_APPROVED = 'PAYMENT_NOT_APPROVED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  APPROVAL_REJECTED = 'APPROVAL_REJECTED',
  EXPIRED = 'EXPIRED',
  TRANSACTION_CANCELED = 'TRANSACTION_CANCELED',
  RESOURCE_ALREADY_EXIST = 'RESOURCE_ALREADY_EXIST',
}

export enum MtnRequestToPayStatus {
  PENDING = 'PENDING',
  SUCCESSFUL = 'SUCCESSFUL',
  FAILED = 'FAILED',
}

export enum MtnPartyIdType {
  MSISDN = 'MSISDN',
  EMAIL = 'EMAIL',
  PARTY_CODE = 'PARTY_CODE',
}
