import { Injectable, BadRequestException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Tenant } from './entities/tenant.entity';
import { UsersService } from '../user/users.service';
import { RoleType } from 'src/common/enums/role-type.enum';
import { CreateTenantWithAdminDto } from './dto/create-tenant-with-admin.dto';
import { User } from '../user/entities/user.entity';

@Injectable()
export class TenantService {
  constructor(
    @InjectRepository(Tenant)
    private readonly tenantRepository: Repository<Tenant>,
    private readonly usersService: UsersService,
  ) {}

  async suggestTenantName(name: string): Promise<string> {
    let base = name.trim();
    let suggestion = base;
    let i = 1;
    while (await this.tenantRepository.findOne({ where: { name: suggestion } })) {
      suggestion = `${base}${i}`;
      i++;
    }
    return suggestion;
  }

  async createTenantWithAdmin(dto: CreateTenantWithAdminDto): Promise<{ tenant: Tenant; admin: User }> {
    // Check if tenant name exists
    const existing = await this.tenantRepository.findOne({ where: { name: dto.name } });
    if (existing) throw new BadRequestException('Tenant name already exists');
    // Slug will be auto-generated by the subscriber
    const tenant = this.tenantRepository.create({
      name: dto.name,
      description: dto.description,
      isActive: true,
    });
    const savedTenant = await this.tenantRepository.save(tenant);
    // Create admin user for tenant, link to tenant by id
    const admin = await this.usersService.createUser({
      username: dto.adminUsername,
      password: dto.adminPassword,
      email: dto.adminEmail,
      role: RoleType.ADMIN,
      tenantId: savedTenant.id, // Link to actual tenant id
    });
    return { tenant: savedTenant, admin };
  }

    async findAll(): Promise<Tenant[]> {
    return this.tenantRepository.find();
  }

  async findOne(id: string): Promise<Tenant | null> {
    return this.tenantRepository.findOne({ where: { id } });
  }

  async update(id: string, data: Partial<Tenant>): Promise<Tenant | null> {
    await this.tenantRepository.update(id, data);
    return this.findOne(id);
  }

  async deactivate(id: string): Promise<Tenant | null> {
    await this.tenantRepository.update(id, { isActive: false });
    return this.findOne(id);
  }

  async remove(id: string): Promise<void> {
    await this.tenantRepository.delete(id);
  }
}
